service: friends-of-maple

custom:
  stage: "${opt:stage, self:provider.stage}"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10
  environment: ${file(env.yml):${self:custom.stage}}

functions:
  postSubscription:
    handler: handler.postSubscription
    events:
      - http:
          path: subscriptions
          method: post
          cors: true
