export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const SET_NAVIGATION = 'SET_NAVIGATION';
export const SET_NAVIGATION_NEXT = 'SET_NEXT_NAVIGATION';
export const SET_NAVIGATION_PREV = 'SET_PREV_NAVIGATION';
export const SET_NAVIGATION_AMOUNT_TO_INFO = 'SET_NAVIGATION_AMOUNT_TO_INFO';

export const SET_AMOUNT = 'SET_AMOUNT';

export const SET_INFORMATION_FIRST_NAME = 'SET_INFORMATION_FIRST_NAME';
export const SET_INFORMATION_LAST_NAME = 'SET_INFORMATION_LAST_NAME';
export const SET_INFORMATION_EMAIL = 'SET_INFORMATION_EMAIL';
export const SET_INFORMATION_PHONE = 'SET_INFORMATION_PHONE';
export const SET_INFORMATION_ADDRESS = 'SET_INFORMATION_ADDRESS';
export const SET_INFORMATION_CITY = 'SET_INFORMATION_CITY';
export const SET_INFORMATION_STATE = 'SET_INFORMATION_STATE';
export const SET_INFORMATION_ZIP = 'SET_INFORMATION_ZIP';
export const CLEAR_INFORMATION = 'CLEAR_INFORMATION';

export const SET_INFORMATION_ERRORS = 'SET_INFORMATION_ERRORS';
export const CLEAR_INFORMATION_ERRORS = 'CLEAR_INFORMATION_ERRORS';

export const SET_PAYMENT_CARD_NUMBER = 'SET_PAYMENT_CARD_NUMBER';
export const SET_PAYMENT_EXPERATION = 'SET_PAYMENT_EXPERATION';
export const SET_PAYMENT_NAME = 'SET_PAYMENT_NAME';
export const SET_PAYMENT_CSV = 'SET_PAYMENT_CSV';
export const SET_PAYMENT_ZIP = 'SET_PAYMENT_ZIP';

export const SET_PAYMENT_ERRORS = 'SET_PAYMENT_ERRORS';
export const CLEAR_PAYMENT_ERRORS = 'CLEAR_PAYMENT_ERRORS';

export const SET_PLEDGE_PROCESSING = 'SET_PLEDGE_PROCESSING';
export const SET_PLEDGE_PAYMENT_TOKEN = 'SET_PLEDGE_PAYMENT_TOKEN';
export const CLEAR_PLEDGE_PAYMENT_TOKEN = 'CLEAR_PLEDGE_PAYMENT_TOKEN';

// Side effects follow
export const VALIDATE_INFORMATION = 'VALIDATE_INFORMATION';
export const VALIDATE_PAYMENT = 'VALIDATE_PAYMENT';

export const POST_PLEDGE = 'POST_PLEDGE';
